apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: depapp
  name: depapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: depapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: depapp
    spec:
      containers:
      - image: bazajee/testapp:tpmyapp
        name: testapp
        resources: {}
status: {}
